### PR TITLE
Added iOS support and .fade.in classes

### PR DESCRIPTION
**Pull request by niftylettuce**

### CODE REVIEW

**Comment by niftylettuce** [comment]
hold off on pullling this for a sec

**Comment by niftylettuce** [comment]
OK, ready for you to merge!

**Comment by JasonGiedymin** [comment]
Need tests by modifying existing, can you add them? (unless I misses it and they're included? I'm on a mobile device)

**Comment by JasonGiedymin** [comment]
Will wait until tonight. If they're not added, I'll go ahead and merge. Then add the tests.

**Comment by JasonGiedymin** [comment]
i will accept this pull request, but tests and the cs script needs to be updated (I'm doing now). You should see this pull request accepted any second now. Will ping this thread back once everything is in order and NPM has been updated. It ain't over yet...

**Comment by JasonGiedymin** [comment]
Because msgs is assigned, there is no need to do a type check using '!=='. Accessing a undefined variable throws exceptions and a need to check typeof is required. Otherwise accessing an undefined property returns undefined so just != is enough. If borking happens it's express's fault. This is why CS only compiles down to '!='.

**Comment by JasonGiedymin** [comment]
Also I don't see "fade in" being actually part of the spec other than in http://twitter.github.com/bootstrap/components.html#navs

**Comment by JasonGiedymin** [comment]
adding additional classes such as 'fade in' can be done via:

```
req.flash('error fade in', 'This is an error.');
```

I added this to the tests.

**Comment by JasonGiedymin** [comment]
NPM Updated:

http://search.npmjs.org/#/express-messages-bootstrap

**Comment by niftylettuce** [comment]
Thanks and sorry I didn't get back quicker.  Appreciate you adding them to the tests too!!!

Great work @JasonGiedymin :+1:

**Comment by JasonGiedymin** [comment]
No thank you for the pull request, regardless of technicalities. The discussion is worth it!

**Pull request merged**
