### PR TITLE
Div Class changes for Alerts

### PR DESCRIPTION
**Pull request by jared**
Updated div classes to match latest bootstrap specification:

alert-info, alert-success, alert-danger, etc.  Updated tests & readme to match.

### CODE REVIEW

**Comment by JasonGiedymin** [comment]
Will look at this tonight and will probably merge this within hours.

**Comment by jared** [comment]
Cool.  Thanks.  I've got one more small change to push along, dealing with dismissing the alerts in the new Bootstrap style; I'll send that along as a separate pull request once the tests are passing.

**Comment by jared** [comment]
One last tweak, thorsteinsson pointed out that the coffeescript file needed updating as well.

**Comment by JasonGiedymin** [comment]
Yes, if you can do the coffeescript file first.

Then use 'coffee -cb'.

I've made the same mistake in the past as well :-)

**Comment by jared** [comment]
Done & done.  Regenerating index.js from index.coffee resulted in no change to the generated .js file... I removed index.js locally, ran 'coffee -cb index.coffee', and checked both git-status and git-diff ... nothing to commit, no untracked files :)

**Comment by JasonGiedymin** [comment]
I will roll this merge in to the main repo but won't push to NPM just yet (as soon as I get more than 15min I'll click the buttons :-) ). There are a few more changes I'll add before NPM sees the new ver (eta < 5 hours).

**Pull request merged**
