### PR TITLE
Changed Links to buttons to avoid page refresh.

### PR DESCRIPTION
**Pull request by romanmt**
I changed the close buttons from links to buttons.
This prevents the page from refreshing when you close a message. 

From the bootstrap docs....

``` html
<div class="alert">
  <button class="close" data-dismiss="alert">×</button>
  <strong>Warning!</strong> Best check yo self, you're not looking too good.
</div>
```

### CODE REVIEW

**Comment by JasonGiedymin** [comment]
This is being implemented in Pull request #11, but I'll merge to give credit as I'm modifying more.

**Comment by JasonGiedymin** [comment]
Ok looks like I can't merge but I can at least give credit.

**Comment by JasonGiedymin** [comment]
NPM Updated with <a> -> <button>

http://search.npmjs.org/#/express-messages-bootstrap

Thanks!

**Comment by romanmt** [comment]
Thank you!

**Pull request closed without merging**
