### PR TITLE
Separation for multiple flash messages

### PR DESCRIPTION
**Pull request by SirUli**
Hello Jason,

during my current project i've discovered, that multiple flash messages are not separated properly from each other. To remedy this issue i've moved the code around a message into the for-loop.

This should not break the tests, although these could be extended for multiple flash messages now.

Best Regards,
Uli

### CODE REVIEW

**Comment by SirUli** [comment]
I didn't change the .coffee File yet but as this is a small change, it could be done quickly.

**Comment by SirUli** [comment]
I've modified all files to comply with the new syntax suggested by the documentation.

**Comment by JasonGiedymin** [comment]
In review.

**Comment by JasonGiedymin** [comment]
Can I haz clean commit too (asking too much?)?

**Comment by SirUli** [comment]
I've corrected it. There was no intention to move this file there. Sorry this is my first time with git.

**Comment by SirUli** [comment]
I will provide you a clean version.

**Pull request closed without merging**
