### PR TITLE
Update to comply with twitter bootstrap 2.0 documentation.

### PR DESCRIPTION
**Pull request by SirUli**
Clean version of my proposed changes. Sorry for the first annoyances.

### CODE REVIEW

**Comment by JasonGiedymin** [comment]
Sweet! I will review again.

**Comment by SirUli** [comment]
Hello Jason,

any chance to get this included?

Thanks in advance!

Best Regards,
Uli

**Comment by niftylettuce** [comment]
?

**Comment by JasonGiedymin** [comment]
I just got back from vacation, looking at it now.

**Comment by JasonGiedymin** [comment]
If all is well you'll see it on NPM in a bit.

**Comment by JasonGiedymin** [comment]
Latest is now v0.0.9 - http://search.npmjs.org/#/express-messages-bootstrap

**Comment by niftylettuce** [comment]
ty

**Pull request merged**
